services:
  - type: worker
    name: tournament-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python script.py
    runtime: python
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
    plan: free
